name = "BDDSolver"
uuid = "95f1ead4-b199-11e9-27b9-1968b166e826"
authors = ["Daniel Spielman <daniel.spielman@yale.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
